-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : sam. 16 mai 2026 à 23:42
-- Version du serveur : 10.4.32-MariaDB
-- Version de PHP : 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `book_shop_db`
--

-- --------------------------------------------------------

--
-- Structure de la table `books`
--

CREATE TABLE `books` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `cover_path` varchar(255) DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `nbr_pages` int(11) NOT NULL DEFAULT 10,
  `publish_year` int(11) DEFAULT 2026,
  `is_published` tinyint(1) NOT NULL DEFAULT 1,
  `category_id` bigint(20) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `books`
--

INSERT INTO `books` (`id`, `title`, `slug`, `description`, `author`, `price`, `cover_path`, `file_path`, `nbr_pages`, `publish_year`, `is_published`, `category_id`, `created_at`, `updated_at`) VALUES
(1, 'Maîtriser Laravel 12 et Volt', 'maitriser-laravel-12-et-volt', 'Un guide complet pour créer des applications web modernes et réactives très rapidement sans se prendre la tête.', NULL, 0, 'covers/blEgpksnhBUnDjJDYLhhiLzhWeAwjXjDKVSrtwGp.png', 'books/jbSHDt0BAHnxit83XD0vpiade2YxQkW31N1gqllr.pdf', 10, 2026, 1, 2, '2026-03-30 17:45:38', '2026-05-11 10:33:16'),
(2, 'Le Guide du Développeur Freelance', 'le-guide-du-developpeur-freelance', 'Comment trouver des clients, structurer ses projets et intégrer des paiements Mobile Money facilement.', NULL, 0, 'covers/ToC1YzvWBq5y0N2Ve538MLBS3g2OrBBOgd5Ky6WY.jpg', 'books/ihPbIHXsEsLXCp2gsPlNpYW3SbjWUyXBZWbcRBw5.pdf', 10, 2026, 1, 1, '2026-03-30 17:45:38', '2026-05-11 10:33:35'),
(3, 'Design UI/UX avec TailwindCSS', 'design-uiux-avec-tailwindcss', 'Créez des interfaces magnifiques et responsives sans jamais quitter vos fichiers Blade.', 'John Doe', 0, 'covers/CIVtvMsSzN6VCpBVpWSb5zJ82dliSZ79AYVP8GVG.png', 'books/ZrbSZx395zsOqs9uLNhnjSQGVi0k18797Fb66g4Q.pdf', 10, 2026, 1, 3, '2026-03-30 17:45:38', '2026-05-11 10:33:48'),
(4, 'Java par la pratique', 'java-par-la-pratique', 'Apprendre le Java de A à Z par la pratique', 'FONHOUO GAUS', 0, 'covers/HQjSoHlvhDDnx3PED8uaRI52p4EsbCcMxl4JpVoF.png', 'books/70uVs1ujJnA8jku8O7qWvTiIcoPvvUGlOi1Em1x4.pdf', 125, 2023, 1, 1, '2026-04-21 01:00:46', '2026-04-21 01:02:47'),
(5, 'Tout savoir sur python', 'tout-savoir-sur-python', 'Tout savoir sur la programmation python', 'Edithson', 2500, 'covers/K4vvM5MJVEOpsR7OGrt8ec0MXdclQlwOmAtJsYK1.jpg', 'books/Bh4Xjh5H80TL4U595Ecjc4nAIUIFQRb5bEYlSTDi.pdf', 256, 2024, 1, NULL, '2026-05-11 12:59:04', '2026-05-11 12:59:04'),
(6, 'Rédiger correctement un Cahier des Charges', 'rediger-correctement-un-cahier-des-charges', 'Optimisez l\'organisation de vos projets numériques en maîtrisant l\'art de rédiger un Cahier des Charges Fonctionnel structuré et professionnel. Ce guide accessible vous accompagne pas à pas pour définir avec précision les besoins de vos utilisateurs, les fonctions de vos produits et les contraintes techniques incontournables. Grâce à des exemples concrets allant du développement PHP au design CSS, vous apprendrez à transformer une idée brute en une feuille de route claire et efficace pour garantir le succès de vos réalisations. Que vous soyez débutant ou développeur aguerri, cet ouvrage est l\'outil indispensable pour professionnaliser votre démarche et sécuriser vos phases de conception.', 'Les Validateurs', 0, 'covers/rediger-correctement-un-cahier-des-charges.png', 'books/rediger-correctement-un-cahier-des-charges.pdf', 12, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:19'),
(7, 'Faire de son programme un Logiciel Libre', 'faire-de-son-programme-un-logiciel-libre', 'Transformez vos projets informatiques en moteurs d\'innovation grâce à ce guide complet et accessible dédié à l\'univers du Logiciel Libre. Que vous soyez attiré par la rigueur de la licence GNU GPL ou la flexibilité du modèle BSD, cet ouvrage vous accompagne pas à pas dans le choix et l\'application concrète du cadre juridique idéal pour vos programmes. En démystifiant des concepts fondamentaux comme le copyleft et l\'accès au code source, ce livre offre aux développeurs toutes les clés nécessaires pour diffuser leurs créations avec assurance tout en rejoignant sereinement la communauté mondiale de l\'Open Source.', 'GuilOooo', 0, 'covers/faire-de-son-programme-un-logiciel-libre.png', 'books/faire-de-son-programme-un-logiciel-libre.pdf', 10, 2010, 1, 7, '2026-05-12 09:35:58', '2026-05-12 11:51:19'),
(8, 'Créez des applications pour Windows 8 en HTML et JavaScript', 'creez-des-applications-pour-windows-8-en-html-et-javascript', 'Maîtrisez le développement d\'applications pour Windows 8 en exploitant la puissance du HTML et du JavaScript grâce à ce guide complet et accessible. De la prise en main de Visual Studio à l\'utilisation avancée des bibliothèques WinRT et WinJS, cet ouvrage vous enseigne comment concevoir des interfaces modernes et fluides parfaitement intégrées à l\'écosystème Microsoft. Vous y découvrirez les secrets du design, la gestion du cycle de vie des programmes et l\'implémentation de fonctionnalités interactives telles que la recherche, le partage et les notifications. Que vous soyez débutant ou développeur web chevronné, ce livre constitue le tremplin idéal pour transformer vos idées en applications professionnelles prêtes à conquérir le Windows Store.', 'XavierBoubert', 0, 'covers/creez-des-applications-pour-windows-8-en-html-et-javascript.png', 'books/creez-des-applications-pour-windows-8-en-html-et-javascript.pdf', 240, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:19'),
(9, 'Concevez votre site web avec PHP et MySQL', 'concevez-votre-site-web-avec-php-et-mysql', 'Plongez dans l\'univers de la programmation web et transformez vos pages statiques en sites dynamiques et interactifs grâce à ce guide complet sur PHP et MySQL. De l\'apprentissage des bases syntaxiques à la gestion avancée des bases de données, cet ouvrage vous accompagne pas à pas dans la création de formulaires sécurisés, le déploiement de sessions utilisateurs et la protection contre les failles de sécurité. Grâce à une pédagogie progressive rythmée par des cas pratiques, vous maîtriserez les outils indispensables pour concevoir des applications web robustes, professionnelles et totalement personnalisées. C\'est la ressource idéale pour tout développeur en herbe souhaitant donner une dimension concrète et performante à ses projets numériques.', 'Mathieu Nebra (Mateo21)', 0, 'covers/concevez-votre-site-web-avec-php-et-mysql.png', 'books/Concevez-votre-site-web-avec-php-et-mysql.pdf', 307, 2013, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(10, 'Centrer en CSS', 'centrer-en-css', 'Maîtrisez enfin l’art complexe du centrage en CSS, l\'un des défis les plus fréquents et pourtant subtils du développement web moderne. Ce guide pratique explore toutes les méthodes natives pour aligner vos éléments avec précision, qu’ils soient horizontaux, verticaux, dans le flux ou positionnés de manière absolue. En finir avec les balises obsolètes devient un jeu d\'enfant grâce à des explications claires sur les propriétés fondamentales et des astuces indispensables pour assurer une compatibilité parfaite entre les différents navigateurs. Que vous soyez un développeur de niveau intermédiaire ou un passionné souhaitant perfectionner ses mises en page, cet ouvrage vous offre les clés pour obtenir un rendu professionnel et structuré en pur CSS.', 'nightmat', 0, 'covers/centrer-en-css.png', 'books/centrer-en-css.pdf', 20, 2012, 1, 5, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(11, 'Améliorez la visibilité de votre site grâce au référencement', 'ameliorez-la-visibilite-de-votre-site-grace-au-referencement', 'Maîtrisez l\'art complexe du référencement naturel pour propulser votre site web au sommet des résultats de recherche Google. Ce guide complet vous accompagne dans l\'optimisation technique de votre structure HTML, la gestion stratégique des mots-clés et l\'exploitation judicieuse du \"jus de lien\" pour maximiser votre autorité en ligne. Vous apprendrez également à renforcer votre notoriété externe via le netlinking et l\'impact des réseaux sociaux, transformant ainsi chaque page en un véritable aimant à visiteurs. C\'est l\'ouvrage de référence indispensable pour quiconque souhaite décrypter les algorithmes modernes et garantir une visibilité pérenne à ses projets numériques.', 'Nassoub', 0, 'covers/ameliorez-la-visibilite-de-votre-site-grace-au-referencement.png', 'books/ameliorez-la-visibilite-de-votre-site-grace-au-referencement.pdf', 129, 2013, 1, 5, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(12, 'Les applications web avec JavaFX', 'les-applications-web-avec-javafx', 'Plongez dans le monde captivant des applications web interactives avec JavaFX. Ce guide complet s\'adresse aux développeurs Java désireux de maîtriser la création de Rich Internet Applications (RIA), de l\'installation des outils à leur déploiement. Vous explorerez la conception d\'interfaces graphiques dynamiques, l\'intégration multimédia et les animations sophistiquées à travers des projets pratiques. Un ouvrage indispensable pour enrichir vos compétences en développement web et donner vie à des expériences utilisateur riches.', 'reemy', 0, 'covers/les-applications-web-avec-javafx.png', 'books/les-applications-web-avec-javafx.pdf', 96, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(13, 'PDO : comprendre et corriger les erreurs les plus fréquentes', 'pdo-comprendre-et-corriger-les-erreurs-les-plus-frequentes', 'Vous êtes développeur PHP et vous vous heurtez régulièrement à des erreurs mystérieuses ou frustrantes avec PDO ? Ce guide essentiel est conçu pour démystifier les pièges courants et vous fournir les outils nécessaires pour comprendre et corriger les problèmes les plus fréquents, qu\'il s\'agisse des options de configuration, de la sécurisation des requêtes ou des subtilités des types de données. Apprenez à interpréter votre code, à anticiper les erreurs et à transformer PDO en un allié puissant et fiable pour toutes vos interactions avec les bases de données. Cessez de perdre du temps à chercher la source de vos bugs et écrivez des applications plus robustes et sécurisées.', 'Guillaume Ch. (cGuille)', 0, 'covers/pdo-comprendre-et-corriger-les-erreurs-les-plus-frequentes.png', 'books/pdo-comprendre-et-corriger-les-erreurs-les-plus-frequentes.pdf', 14, 2011, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(14, 'Apprenez à programmer en Python', 'apprenez-a-programmer-en-python', 'Envie de maîtriser Python, le langage de programmation le plus populaire et polyvalent ? Ce guide complet vous accompagne pas à pas, des bases fondamentales comme les variables, les conditions et les boucles, aux concepts plus avancés tels que les fonctions, les modules et la gestion des exceptions. Grâce à une approche pédagogique progressive, des explications claires et des exercices pratiques, dont un projet concret comme le ZCasino, vous développerez rapidement les compétences pour écrire des programmes structurés. Plongez également dans l\'univers des objets, manipulez les chaînes de caractères, listes, dictionnaires et interagissez avec les fichiers pour concrétiser toutes vos idées.', 'prolixe', 0, 'covers/apprenez-a-programmer-en-python.png', 'books/223267-apprenez-a-programmer-en-python.pdf', 266, 2013, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:21'),
(15, 'Poursuite d\'études après un DUT', 'poursuite-detudes-apres-un-dut', 'Vous êtes titulaire d\'un DUT et la question de votre avenir professionnel ou académique vous préoccupe ? Ce guide essentiel lève le voile sur l\'intégralité des chemins qui s\'offrent à vous, que ce soit une insertion rapide dans le monde du travail ou la poursuite d\'études. Explorez un panorama complet des possibilités, des licences professionnelles aux écoles d\'ingénieurs, en passant par les opportunités à l\'étranger et la réorientation, le tout étayé par des conseils pratiques sur les critères de sélection. Ne laissez plus l\'incertitude vous freiner et construisez sereinement votre projet post-DUT grâce à cette ressource précieuse.', 'Julien Rosset (Darkelfe)', 0, 'covers/poursuite-d-etudes-apres-un-dut.png', 'books/poursuite-d-etudes-apres-un-dut.pdf', 9, 2011, 1, 6, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(16, 'Choisir les bons types de colonne SQL', 'choisir-les-bons-types-de-colonne-sql', 'Vous souhaitez alléger vos bases de données SQL et maximiser leur performance ? Ce guide indispensable vous révèle comment transformer vos tables en choisissant les types de colonne les plus efficaces. Fini les INT et TEXT génériques ! Apprenez à sélectionner les formats numériques, de date, de texte ou à choix multiples adaptés à chaque donnée, afin de diviser par trois ou quatre l\'espace de stockage. Que vous soyez débutant ou expérimenté avec MySQL, vous découvrirez des stratégies pratiques, des règles d\'optimisation clés et des exemples concrets pour concevoir des structures de table SQL légères et performantes.', 'Kyle Katarn', 0, 'covers/choisir-les-bons-types-de-colonne-sql.png', 'books/choisir-les-bons-types-de-colonne-sql.pdf', 16, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(17, 'Mettre des PC en réseau', 'mettre-des-pc-en-reseau', 'Explorez l\'univers du réseautage informatique et apprenez à connecter vos ordinateurs pour échanger des données en toute simplicité. Ce guide pratique vous accompagne pas à pas, de la sélection de la bonne connectique (carte et câble Ethernet) à la configuration des adresses IP et la mise en place d\'un groupe de travail. Conçu pour être accessible aux débutants, il démystifie les concepts essentiels pour que vous puissiez maîtriser le partage de fichiers et de ressources entre vos machines. Lancez-vous dans la création de votre propre réseau local avec confiance et autonomie.', 'ShigeruM', 0, 'covers/mettre-des-pc-en-reseau.png', 'books/mettre-des-pc-en-reseau.pdf', 10, 2011, 1, 7, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(18, 'Créez des applications pour iPhone, iPad et iPod Touch', 'creez-des-applications-pour-iphone-ipad-et-ipod-touch', 'Découvrez comment donner vie à vos idées d\'applications pour iPhone, iPad et iPod Touch grâce à ce guide complet et accessible. De l\'installation de votre environnement de développement à la maîtrise approfondie de l\'Objective-C et la conception d\'interfaces graphiques intuitives, chaque étape est couverte pour vous transformer en développeur iOS aguerri. Enrichi de projets concrets, comme la création d\'un jeu de Mastermind, ce livre vous fournira les compétences pratiques indispensables pour créer des applications performantes et attrayantes. Préparez-vous à concrétiser vos projets et à les voir s\'exécuter sur les appareils mobiles d\'Apple.', 'MichelMartin', 0, 'covers/creez-des-applications-pour-iphone-ipad-et-ipod-touch.png', 'books/creez-des-applications-pour-iphone-ipad-et-ipod-touch.pdf', 461, 2013, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(19, 'Apprenez à créer votre site web avec HTML5 et CSS3', 'apprenez-a-creer-votre-site-web-avec-html5-et-css3', 'Vous rêvez de concevoir et de donner vie à votre propre site web ? Ce guide complet est votre passeport pour l\'univers de la création web, même sans aucune expérience préalable. Apprenez à structurer le contenu avec les toutes dernières fonctionnalités de HTML5 et à le sublimer grâce aux puissantes mises en forme de CSS3. Lancez-vous et transformez vos idées en sites internet modernes et fonctionnels.', 'Mathieu Nebra (Mateo21)', 0, 'covers/apprenez-a-creer-votre-site-web-avec-html5-et-css3.png', 'books/apprenez-a-creer-votre-site-web-avec-html5-et-css3.pdf', 248, 2013, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(20, 'Créer un espace membre pour son site', 'creer-un-espace-membre-pour-son-site', 'Transformez votre site web en une plateforme interactive et dynamique avec ce guide pratique dédié à la création d\'un espace membre complet. Vous y découvrirez comment mettre en place les fonctions essentielles, de l\'inscription et la connexion sécurisée à la gestion des profils et l\'administration des utilisateurs. Idéal pour les développeurs familiers avec PHP/MySQL et HTML/CSS, cet ouvrage propose une approche pas à pas, jalonnée d\'exercices corrigés, pour construire les fondations d\'une communauté en ligne. Maîtrisez les bases essentielles et offrez à vos visiteurs une expérience personnalisée et enrichie sur votre site.', 'Mr. Black', 0, 'covers/creer-un-espace-membre-pour-son-site.png', 'books/creer-un-espace-membre-pour-son-site.pdf', 97, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(21, 'Comment créer un jeu vidéo ?', 'comment-creer-un-jeu-video', 'Rêvez-vous de passer du côté du joueur à celui du créateur ? Ce guide, conçu pour les débutants absolus, vous prend par la main pour vous montrer comment créer un jeu vidéo de A à Z, sans aucune connaissance préalable en informatique. Explorez les composants essentiels, des graphismes aux musiques en passant par la programmation, et apprenez à structurer votre projet, de l\'idée initiale jusqu\'à la constitution d\'une équipe. Transformez enfin votre passion en une réalisation concrète et maîtrisez les bases de la conception de jeux vidéo.', 'Rastagong', 0, 'covers/comment-creer-un-jeu-video.png', 'books/comment-creer-un-jeu-video.pdf', 12, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:21'),
(22, 'Créez votre propre package', 'creez-votre-propre-package', 'Fini les préambules répétitifs et les copier-coller incessants ! Ce guide pratique vous ouvre les portes de la personnalisation avancée de LaTeX en vous enseignant à créer vos propres packages sur mesure. Apprenez à structurer, optimiser et partager vos extensions, intégrant des options et des conditions pour adapter parfaitement votre environnement de travail. Transformez votre utilisation de LaTeX en une expérience plus fluide et efficace, et devenez un maître de la composition typographique.', 'sp.conductos', 0, 'covers/creez-votre-propre-package.png', 'books/creez-votre-propre-package.pdf', 13, 2009, 1, 6, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(23, '[TP] Pendu', 'tp-pendu', 'Découvrez comment créer une version graphique du célèbre jeu du Pendu grâce à ce tutoriel pratique et accessible, idéal pour les développeurs C souhaitant maîtriser SDL et SDL_ttf. Ce guide pas à pas vous accompagne pour transformer le jeu de console en une expérience visuellement enrichie, avec des images dynamiques et une gestion avancée du texte. Profitez d\'un projet clé en main : toutes les ressources (graphismes, polices, dictionnaire) sont fournies, accompagnées d\'une correction détaillée et de nombreuses pistes d\'améliorations. Un excellent exercice pour consolider vos compétences en programmation de jeux.', 'Triviak', 0, 'covers/tp-pendu.png', 'books/TP-pendu.pdf', 29, 2010, 1, 7, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(24, 'jQuery, dynamisez vos pages plus simplement !', 'jquery-dynamisez-vos-pages-plus-simplement', 'Fatigué de la complexité de JavaScript et des défis de compatibilité navigateur ? Ce livre vous invite à découvrir jQuery, la bibliothèque qui simplifie radicalement la dynamisation de vos pages web. Du classique \"Hello World\" à la manipulation avancée du contenu et des attributs, apprenez à exploiter les puissants sélecteurs et méthodes de jQuery pour créer des interfaces fluides. Adoptez une syntaxe élégante et homogène qui vous permettra de développer plus rapidement, sans vous soucier des spécificités inter-navigateurs, et de libérer tout le potentiel de vos projets web.', 'Alex-D', 0, 'covers/jquery-dynamisez-vos-pages-plus-simplement.png', 'books/jquery-dynamisez-vos-pages-plus-simplement.pdf', 30, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(25, 'Programmez en orienté objet en PHP', 'programmez-en-oriente-objet-en-php', 'Passez de la programmation procédurale à l\'excellence orientée objet en PHP grâce à ce guide complet et pratique. Vous y explorerez les fondations essentielles, de la création de classes et d\'objets à l\'encapsulation et l\'héritage, en les appliquant directement via des ateliers concrets comme un mini-jeu de combat et la gestion de données en base. Poussez ensuite vos compétences avec les méthodes magiques, les interfaces, la gestion des exceptions, les traits et la réflexivité, pour architecturer des applications PHP robustes, évolutives et professionnelles.', 'Victor Thuillier (vyk12)', 0, 'covers/programmez-en-oriente-objet-en-php.png', 'books/programmez-en-oriente-objet-en-php.pdf', 332, 2013, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(26, '[CSS] Les compteurs', 'css-les-compteurs', 'Découvrez comment les compteurs CSS révolutionnent la numérotation de vos contenus web en automatisant chapitres, paragraphes et sections sans modifier une ligne de votre code HTML. Ce guide pratique vous apprendra à initialiser, incrémenter et insérer ces compteurs pour créer des structures cohérentes et professionnelles, à la manière des livres. Facile d\'accès, il vous montrera comment obtenir une présentation dynamique et parfaitement organisée de vos pages, tout en explorant des techniques avancées comme les compteurs imbriqués. Optimisez dès maintenant la présentation de vos articles et sites web avec une solution CSS élégante et efficace.', 'Itello', 0, 'covers/css-les-compteurs.png', 'books/css-les-compteurs.pdf', 9, 2012, 1, 5, '2026-05-12 09:35:58', '2026-05-12 11:51:20'),
(27, 'La balise <canvas> avec JavaScript', 'la-balise-canvas-avec-javascript', 'Plongez dans l\'univers fascinant de la création graphique web avec \"La balise <canvas> avec JavaScript\" ! Ce guide accessible vous initie étape par étape aux fondamentaux du dessin et de l\'animation à l\'aide de l\'élément <canvas> d\'HTML5 et de JavaScript. Apprenez à manipuler les formes, les coordonnées et les bases de l\'animation, avec un projet pratique de balle rebondissante pour consolider vos acquis. Maîtrisez les outils essentiels pour donner vie à vos interfaces interactives.', 'Renan Gehan (rgehan)', 0, 'covers/la-balise-canvas-avec-javascript.png', 'books/La-balise-canvas-avec-javascript.pdf', 14, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:21'),
(28, 'Le JavaScript moderne', 'le-javascript-moderne', 'Loin de son image passée, JavaScript s\'est imposé comme un pilier incontournable du développement moderne, du navigateur au serveur, et même aux applications de bureau. Ce livre vous invite à explorer l\'évolution fulgurante de ce langage, de ses origines à son statut d\'assembleur du web. Découvrez ses capacités actuelles et futures grâce aux innovations d\'ECMAScript Harmony, aux modules et aux autres nouveautés qui le rendent plus puissant et polyvalent que jamais. Un guide essentiel pour tout programmeur souhaitant maîtriser les multiples facettes de ce langage dynamique et omniprésent.', 'artragis', 0, 'covers/le-javascript-moderne.png', 'books/le-javascript-moderne.pdf', 17, 2012, 1, 4, '2026-05-12 09:35:58', '2026-05-12 11:51:21'),
(29, '[SQL] Sélection multi- tables', 'sql-selection-multi-tables', 'Maîtrisez la sélection de données complexes en SQL en explorant des techniques performantes pour interroger plusieurs tables, sans recourir aux jointures traditionnelles. Ce guide pratique vous accompagnera depuis la conception structurée de vos tables (MCD, clés étrangères) jusqu\'à l\'implémentation de solutions élégantes via les requêtes imbriquées. Idéal pour optimiser vos bases de données et diversifier vos approches d\'interrogation, il vous permettra de manipuler les informations avec une clarté et une efficacité accrues.', 'FlYos', 0, 'covers/sql-selection-multi-tables.png', 'books/sql-selection-multi-tables.pdf', 8, 2011, 1, 7, '2026-05-12 09:35:58', '2026-05-12 11:51:21'),
(30, 'Analysez des données avec Excel', 'analysez-des-donnees-avec-excel', 'Maîtrisez Excel de A à Z pour transformer vos données brutes en informations stratégiques grâce à ce guide complet et progressif. De la prise en main du logiciel aux formules avancées, en passant par les tableaux croisés dynamiques, les graphiques percutants et les outils de simulation, vous développerez une expertise solide en analyse de données. Allez plus loin en découvrant les bases de la programmation VBA pour automatiser vos tâches et créer des solutions personnalisées, décuplant ainsi la puissance d\'Excel. Idéal pour les débutants comme pour ceux souhaitant perfectionner leurs compétences, ce livre est la ressource indispensable pour exploiter pleinement le potentiel de cet outil incontournable.', 'bat538 ,', 0, 'covers/analysez-des-donnees-avec-excel.png', 'books/200966-analysez-des-donnees-avec-excel.pdf', 249, 2013, 1, 6, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(31, 'Stop aux pourriels (spams)', 'stop-aux-pourriels-spams', 'Marre des spams qui inondent votre boîte de réception après avoir publié votre adresse e-mail en ligne ? Ce livre est votre bouclier ! \"Stop aux pourriels (spams)\" vous offre un guide indispensable pour déjouer les robots collecteurs, en vous présentant des techniques ingénieuses exploitant xHTML/CSS, JavaScript et PHP. Apprenez à transformer et crypter votre adresse sans la rendre illisible pour vos visiteurs, et dites adieu aux messages indésirables.', 'Dark Lemon', 0, 'covers/stop-aux-pourriels-spams.png', 'books/stop-aux-pourriels-spams.pdf', 13, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(32, 'Maîtrisez les bases de données avec QtSQL', 'maitrisez-les-bases-de-donnees-avec-qtsql', 'Découvrez comment intégrer efficacement les bases de données dans vos projets Qt grâce à ce guide pratique et accessible. De la préparation de votre environnement à la connexion, en passant par l\'exécution de requêtes et le traitement des données avec QtSQL, chaque étape est expliquée clairement. Idéal pour les développeurs possédant déjà des bases en C++, Qt et SQL, cet ouvrage vous mènera pas à pas vers la maîtrise des fonctionnalités essentielles de gestion de données, même sans interface graphique. Lancez-vous et enrichissez vos applications Qt avec une gestion de données robuste et performante.', 'Dadouchi A.', 0, 'covers/maitrisez-les-bases-de-donnees-avec-qtsql.png', 'books/maitrisez-les-bases-de-donnees-avec-qtsql.pdf', 8, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(33, 'Les espaces de noms en PHP', 'les-espaces-de-noms-en-php', 'Maîtrisez les espaces de noms en PHP, une fonctionnalité essentielle pour tout développeur souhaitant professionnaliser son code. Dites adieu aux conflits de noms entre classes, fonctions et constantes, même lorsque vous intégrez de multiples bibliothèques. Ce guide pratique de niveau intermédiaire vous accompagnera pas à pas, de la déclaration simple aux sous-namespaces et à la gestion des alias, pour une architecture applicative claire et robuste.', 'Victor Thuillier (vyk12)', 0, 'covers/les-espaces-de-noms-en-php.png', 'books/les-espaces-de-noms-en-php.pdf', 12, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(34, 'Simplifiez-vous la vie avec LESS', 'simplifiez-vous-la-vie-avec-less', 'Découvrez comment **Simplifiez-vous la vie avec LESS** et transformez radicalement votre approche du CSS. Ce guide complet vous montrera comment ce pré-processeur puissant résout les problèmes de code répétitif et d\'organisation, grâce à l\'introduction des variables, des classes abstraites (mixins) et de l\'imbrication des sélecteurs. Que vous souhaitiez une installation côté client ou serveur (Node.js), cet ouvrage vous accompagnera pas à pas vers un CSS plus propre, plus modulaire et infiniment plus facile à maintenir, quelle que soit votre expérience en développement web.', 'Iso', 0, 'covers/simplifiez-vous-la-vie-avec-less.png', 'books/simplifiez-vous-la-vie-avec-less.pdf', 10, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(35, 'Comment contribuer à un projet libre sans écrire une ligne de code ?', 'comment-contribuer-a-un-projet-libre-sans-ecrire-une-ligne-de-code', 'Découvrez comment devenir un acteur clé de l’écosystème open source sans avoir besoin de maîtriser le moindre langage de programmation. Ce guide pratique explore des leviers essentiels tels que la rédaction de documentation, la traduction d\'interfaces ou le soutien aux nouveaux utilisateurs pour faire progresser durablement vos logiciels favoris. En mettant vos compétences rédactionnelles, linguistiques ou relationnelles au service de la communauté, vous contribuez directement à la qualité et à la pérennité des outils que vous utilisez au quotidien. C\'est l\'ouvrage indispensable pour quiconque souhaite passer de simple utilisateur à contributeur actif, tout en embrassant pleinement les valeurs du partage et de l\'entraide.', 'Sithran', 0, 'covers/comment-contribuer-a-un-projet-libre-sans-ecrire-une-ligne-de-code.png', 'books/comment-contribuer-a-un-projet-libre-sans-ecrire-une-ligne-de-code.pdf', 5, 2010, 1, 7, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(36, 'Apprenez le fonctionnement des réseaux TCP/IP', 'apprenez-le-fonctionnement-des-reseaux-tcpip', 'Plongez au cœur des réseaux informatiques et maîtrisez les fondamentaux du TCP/IP avec ce guide complet et progressif. Il vous révélera, étape par étape, comment les machines communiquent localement, dialoguent entre réseaux et interagissent via les applications. Riche en explications claires, en exercices pratiques et en mises en situation concrètes (routage, Wireshark, DHCP, DNS), cet ouvrage vous dotera des compétences essentielles pour comprendre, configurer et optimiser le fonctionnement de l\'Internet. Que vous soyez débutant ou souhaitiez consolider vos acquis, ce livre est votre passeport pour l\'univers des réseaux.', 'Romain Guichard (Caelifer) ,', 0, 'covers/apprenez-le-fonctionnement-des-reseaux-tcp-ip.png', 'books/346829-apprenez-le-fonctionnement-des-reseaux-tcp-ip.pdf', 219, 2013, 1, 5, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(37, 'Créer un mini-RPG en JavaScript avec canvas', 'creer-un-mini-rpg-en-javascript-avec-canvas', 'Lancez-vous dans l\'univers de la création de jeux vidéo avec \"Créer un mini-RPG en JavaScript avec canvas\". Ce guide s\'adresse aux développeurs intermédiaires maîtrisant HTML, JavaScript objet et AJAX, souhaitant bâtir les fondations d\'un jeu de rôle dynamique. Vous y apprendrez à concevoir des cartes interactives, animer des personnages, gérer la caméra et intégrer des éléments d\'interface. Une ressource essentielle pour donner vie à votre propre mini-RPG solo, étape par étape.', 'Sébastien CAPARROS (sebcap26)', 0, 'covers/creer-un-mini-rpg-en-javascript-avec-canvas.png', 'books/creer-un-mini-rpg-en-javascript-avec-canvas.pdf', 34, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(38, 'Des applications ultra-rapides avec Node.js', 'des-applications-ultra-rapides-avec-nodejs', 'Maîtrisez Node.js, l\'outil incontournable pour les développeurs web désireux de créer des applications ultra-rapides et hautement performantes. De la compréhension de ses mécanismes fondamentaux à la structuration d\'applications robustes avec Express.js, en passant par la gestion des modules via NPM et la mise en œuvre du temps réel avec Socket.io, chaque aspect est abordé avec des exemples concrets et des TPs pratiques. Conçu pour les développeurs JavaScript expérimentés, cet ouvrage vous offre les clés pour exploiter pleinement le potentiel de Node.js et concrétiser vos projets les plus ambitieux.', 'Mathieu Nebra (Mateo21)', 0, 'covers/des-applications-ultra-rapides-avec-node-js.png', 'books/des-applications-ultra-rapides-avec-node-js.pdf', 81, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(39, 'Un livre d\'or', 'un-livre-dor', 'Apprenez à dynamiser votre site web en créant un livre d\'or interactif grâce à ce guide pratique et accessible conçu par Mathieu Nebra. Ce tutoriel pas à pas vous enseigne comment maîtriser les bases de données MySQL et sécuriser vos formulaires pour permettre à vos visiteurs de laisser une trace de leur passage en toute simplicité. Vous y découvrirez également les secrets de la pagination automatique en PHP afin d\'organiser un grand volume de messages de manière fluide et professionnelle. C\'est l\'outil pédagogique idéal pour recueillir des retours précieux et renforcer l\'interactivité de votre projet web dès ses premiers pas.', 'Mathieu Nebra (Mateo21)', 0, 'covers/un-livre-d-or.png', 'books/un-livre-d-or.pdf', 9, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(40, 'Votre site PHP (presque) complet : architecture MVC et bonnes pratiques', 'votre-site-php-presque-complet-architecture-mvc-et-bonnes-pratiques', 'Passez du stade de débutant à celui de développeur averti en apprenant à structurer vos projets web selon l\'architecture MVC et les standards professionnels les plus exigeants. À travers la réalisation concrète d\'un espace membre complet, ce guide vous enseigne comment séparer efficacement vos couches de données tout en appliquant des règles de sécurité rigoureuses pour protéger durablement vos utilisateurs. Vous y découvrirez des outils robustes pour simplifier la gestion de vos bases de données et de vos formulaires, garantissant ainsi un code lisible, évolutif et facile à maintenir. Idéal pour approfondir vos connaissances techniques, cet ouvrage constitue un véritable tremplin pour bâtir des applications web performantes dans les règles de l\'art.', 'Savageman', 0, 'covers/votre-site-php-presque-complet-architecture-mvc-et-bonnes-pratiques.png', 'books/votre-site-php-presque-complet-architecture-mvc-et-bonnes-pratiques.pdf', 54, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(41, 'Modélisation par révolution', 'modelisation-par-revolution', 'Découvrez l\'art de la modélisation par révolution, une technique simple et performante pour transformer vos tracés en objets 3D élégants. Ce guide pratique vous accompagne pas à pas dans la maîtrise des courbes et du modificateur « Lathe » afin de concevoir avec aisance des volumes sophistiqués comme des verres, des vases ou des pièces d\'échecs. Accessible aux débutants, l\'ouvrage dévoile les secrets d\'une méthode inspirée de la poterie pour obtenir des résultats professionnels et harmonieux en quelques clics seulement. Optimisez dès maintenant votre flux de travail et donnez une nouvelle dimension à vos créations numériques grâce à cette approche pédagogique et concrète.', 'révolution', 0, 'covers/modelisation-par-revolution.png', 'books/modelisation-par-revolution.pdf', 6, 2010, 1, 7, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(42, 'Créer son forum de toutes pièces', 'creer-son-forum-de-toutes-pieces', 'Affranchissez-vous des solutions clés en main et apprenez à bâtir votre propre forum de discussion en partant de zéro grâce à ce guide complet et accessible. Étape par étape, vous maîtriserez le développement des fonctionnalités essentielles, de la gestion sécurisée des profils et de la messagerie privée jusqu\'à la mise en place d\'une interface d\'administration robuste pour modérer efficacement votre communauté. L’ouvrage explore également l\'intégration d\'options avancées comme un système d\'amis ou le suivi des messages non lus afin d\'offrir une expérience utilisateur véritablement professionnelle. Ce manuel est l\'outil idéal pour tout développeur souhaitant gagner en autonomie et concevoir un espace d\'échange unique, parfaitement adapté à ses besoins.', 'Tadzoa', 0, 'covers/creer-son-forum-de-toutes-pieces.png', 'books/creer-son-forum-de-toutes-pieces.pdf', 164, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(43, 'La gestion des erreurs et des problèmes HTML', 'la-gestion-des-erreurs-et-des-problemes-html', 'Maîtrisez l\'art délicat du débogage web grâce à ce guide complet dédié à la résolution des problèmes HTML et CSS les plus fréquents. À travers une approche méthodique et concrète, cet ouvrage vous apprend à identifier rapidement l\'origine des déformations de mise en page et à dompter les subtilités complexes du positionnement ou de l\'alignement vertical. Idéal pour transformer vos erreurs d\'affichage en une expertise technique solide, ce manuel constitue une référence indispensable pour tout développeur souhaitant concevoir des interfaces web impeccables et professionnelles.', 'Ciphered', 0, 'covers/la-gestion-des-erreurs-et-des-problemes-html.png', 'books/la-gestion-des-erreurs-et-des-problemes-html.pdf', 17, 2010, 1, 5, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(44, 'Créez votre menu interactif en images en HTML/CSS !', 'creez-votre-menu-interactif-en-images-en-htmlcss', 'Plongez dans l\'univers du web design moderne en apprenant à concevoir un menu interactif élégant exclusivement à l\'aide de HTML5 et CSS3. Sans aucune ligne de JavaScript, cet ouvrage vous guide pas à pas dans la création d\'une interface visuelle dynamique intégrant des effets de zoom et des transitions fluides particulièrement esthétiques. Vous maîtriserez l\'art de l\'ergonomie grâce à une navigation optimisée pour le survol et le clavier, tout en explorant diverses variantes pour adapter vos menus à tous vos projets. Transformez vos simples listes de liens en une galerie d\'images interactive et professionnelle qui saura captiver vos utilisateurs dès le premier coup d\'œil.', 'Dwayn ,', 0, 'covers/creez-votre-menu-interactif-en-images-en-html-css.png', 'books/creez-votre-menu-interactif-en-images-en-html-css.pdf', 30, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(45, 'Introduction à l\'injection de dépendances en PHP', 'introduction-a-linjection-de-dependances-en-php', 'Fatigué des dépendances rigides et du manque de flexibilité dans vos applications PHP ? Ce guide pratique vous ouvre les portes de l\'injection de dépendances, un patron de conception essentiel pour maîtriser le cycle de vie de vos objets et concevoir un code plus robuste. Apprenez à mettre en œuvre cette technique avec des conteneurs de services, tels que Pimple, afin de créer des applications modulaires, facilement configurables et à la maintenabilité accrue. Améliorez significativement la qualité et l\'évolutivité de vos projets PHP en adoptant les meilleures pratiques de la programmation orientée objet.', 'vincent1870', 0, 'covers/introduction-a-l-injection-de-dependances-en-php.png', 'books/495641-introduction-a-l-injection-de-dependances-en-php.pdf', 16, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(46, 'Adopter un style de programmation clair avec le modèle MVC', 'adopter-un-style-de-programmation-clair-avec-le-modele-mvc', 'Fatigué de naviguer dans un code désordonné et difficile à maintenir ? Plongez dans les principes du modèle MVC avec ce guide pratique pour structurer vos applications PHP de manière claire et élégante. De la théorie des Contrôleurs, Modèles et Vues à l\'organisation optimisée de vos fichiers, vous construirez un système de news complet et découvrirez des pistes pour aller plus loin, comme l\'utilisation de frameworks. Adoptez dès maintenant les bonnes pratiques qui transformeront la lisibilité et l\'évolutivité de vos projets de développement web.', 'vincent1870', 0, 'covers/adopter-un-style-de-programmation-clair-avec-le-modele-mvc.png', 'books/adopter-un-style-de-programmation-clair-avec-le-modele-mvc.pdf', 11, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(47, 'Propulsez votre site avec WordPress', 'propulsez-votre-site-avec-wordpress', 'De la première installation à l\'optimisation avancée, ce guide complet vous offre toutes les clés pour maîtriser WordPress, le CMS le plus populaire du web. Apprenez à manipuler son interface d\'administration, à gérer publications et médias, et à personnaliser son apparence avec des thèmes et des extensions. Allez bien au-delà de l\'utilisation de base en développant vos propres thèmes et plugins sur mesure, et en optimisant votre site pour le référencement et la performance avant de le mettre en production. Grâce à des explications claires et de nombreux travaux pratiques, vous serez armé pour créer et propulser un site WordPress unique, professionnel et performant.', 'Midnight Falcon', 0, 'covers/propulsez-votre-site-avec-wordpress.png', 'books/propulsez-votre-site-avec-wordpress.pdf', 112, 2014, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(48, 'Triggers et vues matérialisées (MySQL)', 'triggers-et-vues-materialisees-mysql', 'Optimisez la performance et l\'intégrité de vos bases de données MySQL avec ce tutoriel essentiel sur les triggers et les vues matérialisées. Découvrez comment les vues matérialisées peuvent servir de cache pour accélérer drastiquement vos requêtes, tandis que les triggers vous permettront d\'automatiser des tâches cruciales comme l\'historisation des données ou le calcul de valeurs par défaut. Grâce à des exemples concrets et des mises en garde pratiques, ce guide intermédiaire vous outille pour maîtriser ces puissants mécanismes et bâtir des applications plus robustes et réactives.', 'Lord Casque Noir', 0, 'covers/triggers-et-vues-materialisees-mysql.png', 'books/triggers-et-vues-materialisees-mysql.pdf', 26, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(49, 'Atomik Framework : un framework PHP simple et léger', 'atomik-framework-un-framework-php-simple-et-leger', 'Plongez dans l\'univers d\'Atomik Framework, un framework PHP ultra-léger et intuitif, idéal pour le développement rapide de vos projets web. Ce guide vous révèle comment exploiter la puissance de cet outil performant, développé en France, qui mise sur la simplicité et la modularité grâce à un système de plugins efficace. De son installation à la configuration avancée, en passant par la maîtrise de ses fonctions clés, vous apprendrez à construire des sites réactifs de petite à moyenne envergure. Optimisez votre workflow et découvrez une approche minimaliste mais complète pour vos applications PHP.', 'Warshadow', 0, 'covers/atomik-framework-un-framework-php-simple-et-leger.png', 'books/Atomik-framework-un-framework-php-simple-et-leger.pdf', 11, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:21'),
(50, 'Comment faire une page ayant la même hauteur que le navigateur ?', 'comment-faire-une-page-ayant-la-meme-hauteur-que-le-navigateur', 'Vous souhaitez que votre page web s\'adapte parfaitement à la hauteur du navigateur de chaque visiteur ? Ce guide pratique vous dévoile des techniques claires en CSS et JavaScript pour concevoir des mises en page dynamiques qui s\'ajustent automatiquement. Maîtrisez cette problématique courante du développement web avec des solutions accessibles, garantissant une expérience utilisateur optimisée et une meilleure compatibilité entre navigateurs, même les plus anciens. Idéal pour les développeurs de tout niveau, ce tutoriel \"facile\" vous aidera à créer des designs plus réactifs et visuellement cohérents.', 'Anonyme', 0, 'covers/comment-faire-une-page-ayant-la-meme-hauteur-que-le-navigateur.png', 'books/145147-comment-faire-une-page-ayant-la-meme-hauteur-que-le-navigateur.pdf', 8, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(51, 'Calcul d\'une expression mathématique', 'calcul-dune-expression-mathematique', 'Explorez les mystères de l\'interprétation des expressions mathématiques avec cet ouvrage pratique et approfondi ! Apprenez à construire votre propre calculatrice, capable de décoder des expressions complexes, en maîtrisant des concepts clés tels que l\'analyse lexicale, l\'analyse syntaxique (via la BNF) et la manipulation d\'arbres syntaxiques abstraits. Ce guide essentiel vous offre une première approche concrète de la compilation, transformant une simple chaîne de caractères en un résultat calculé. Une ressource indispensable pour tout développeur désireux de comprendre comment les ordinateurs traitent le langage mathématique.', 'robocop', 0, 'covers/calcul-d-une-expression-mathematique.png', 'books/calcul-d-une-expression-mathematique.pdf', 11, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(52, 'jQuery : écrivez moins pour faire plus !', 'jquery-ecrivez-moins-pour-faire-plus', 'Plongez dans l\'univers de jQuery et transformez votre manière de développer des interfaces web : écrivez moins de code, mais réalisez des fonctionnalités bien plus riches et dynamiques. Cet ouvrage complet vous guide depuis les bases de l\'installation et des sélecteurs jusqu\'à la manipulation experte du DOM, la gestion des attributs et des formulaires, ainsi que la création d\'animations fluides et d\'effets visuels. Riche en exemples et travaux pratiques, il aborde également les sujets avancés comme la gestion déléguée des événements et les espaces de noms, pour une interactivité web sans précédent. Maîtrisez cette bibliothèque incontournable, adoptée par les géants du web, et optimisez vos projets pour une expérience utilisateur remarquable.', 'tit_toinou', 0, 'covers/jquery-ecrivez-moins-pour-faire-plus.png', 'books/jquery-ecrivez-moins-pour-faire-plus.pdf', 86, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(53, 'Un compte à rebours en PHP', 'un-compte-a-rebours-en-php', 'Envie d\'intégrer un compte à rebours dynamique et personnalisé à votre site web ? Ce guide pratique en PHP, d\'une difficulté annoncée « Facile », vous accompagne pas à pas pour créer un décompte efficace, à l\'image de celui avant Noël. Vous maîtriserez les concepts clés comme les timestamps et les conversions de temps, avec une option JavaScript pour ceux qui souhaitent aller plus loin. Idéal pour les développeurs PHP cherchant à ajouter une touche interactive à leurs projets, ce livre vous prouvera qu\'un tel script est à la portée de tous.', 'SpriteWare', 0, 'covers/un-compte-a-rebours-en-php.png', 'books/un-compte-a-rebours-en-php.pdf', 9, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(54, 'Simplifiez vos développements JavaScript avec jQuery', 'simplifiez-vos-developpements-javascript-avec-jquery', 'Plongez au cœur de jQuery avec ce guide indispensable pour transformer et simplifier vos développements JavaScript. De l\'installation aux techniques avancées, maîtrisez la manipulation du DOM, la gestion événementielle et la création d\'animations fluides, le tout illustré par des exemples concrets et des projets pratiques. Ce livre vous offre les clés pour concevoir des interfaces web dynamiques et performantes avec une efficacité redoutable, vous permettant d\'économiser un temps précieux. Adoptez jQuery et portez vos compétences de développeur à un niveau supérieur.', 'MichelMartin', 0, 'covers/simplifiez-vos-developpements-javascript-avec-jquery.png', 'books/simplifiez-vos-developpements-javascript-avec-jquery.pdf', 266, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(55, 'Découvrez la puissance de jQuery UI', 'decouvrez-la-puissance-de-jquery-ui', 'Libérez tout le potentiel de vos interfaces web avec \"Découvrez la puissance de jQuery UI\", le guide indispensable pour tout développeur désireux de créer des expériences utilisateur dynamiques et intuitives. Cet ouvrage vous plonge au cœur des interactions fondamentales – du Drag & Drop à la sélection et au redimensionnement – et vous initie aux widgets essentiels tels que les menus accordéon, les barres de progression et l\'autocomplétion. Grâce à des explications claires et des ateliers pratiques, vous apprendrez à implémenter facilement des fonctionnalités avancées, résolvant les défis de compatibilité et d\'accessibilité. Maîtrisez jQuery UI pour concevoir des applications web modernes, performantes et visuellement attrayantes.', 'Sainior', 0, 'covers/decouvrez-la-puissance-de-jquery-ui.png', 'books/decouvrez-la-puissance-de-jquery-ui.pdf', 67, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(56, 'Apprenez à programmer en Java', 'apprenez-a-programmer-en-java', 'Plongez dans l\'univers de la programmation avec ce guide complet qui vous accompagne de vos premiers pas en Java jusqu\'à la maîtrise des concepts les plus avancés du langage. Vous apprendrez à structurer des applications robustes grâce à l\'approche orientée objet et aux design patterns, tout en découvrant comment créer des interfaces graphiques interactives et gérer des tâches simultanées. Ponctué de travaux pratiques concrets et de conseils méthodologiques, cet ouvrage pédagogique constitue le tremplin idéal pour transformer vos idées en logiciels professionnels et performants. Que vous soyez totalement débutant ou souhaitiez consolider vos bases, cette référence indispensable vous offre une progression fluide pour devenir un développeur Java accompli.', 'cysboy', 0, 'covers/apprenez-a-programmer-en-java.png', 'books/10601-apprenez-a-programmer-en-java.pdf', 534, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(57, 'Autour de la fonction exponentielle et ses constructions', 'autour-de-la-fonction-exponentielle-et-ses-constructions', 'Explorez les secrets de l\'analyse mathématique à travers cet ouvrage captivant qui propose une immersion inédite dans les multiples constructions de la fonction exponentielle. En reliant rigoureusement les équations différentielles aux transformations de sommes en produits, ce guide permet de dépasser les simples bases scolaires pour saisir toute l\'unité et la puissance de ce concept fondamental. Grâce à une approche pédagogique stimulante et ponctuée de notes culturelles, les lecteurs avides d\'approfondissement découvriront comment des points de départ variés convergent vers une même réalité mathématique universelle.', 'louisclem', 0, 'covers/autour-de-la-fonction-exponentielle-et-ses-constructions.png', 'books/autour-de-la-fonction-exponentielle-et-ses-constructions.pdf', 17, 2011, 1, 6, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(58, 'Créer un menu circulaire', 'creer-un-menu-circulaire', 'Apprenez à transformer l\'interface de votre site web en concevant un menu circulaire interactif et élégant qui saura captiver vos visiteurs par son originalité. Ce guide pratique vous accompagne pas à pas dans l\'utilisation conjointe du HTML, du CSS et du JavaScript pour créer une animation fluide basée sur les principes fondamentaux de la trigonométrie. En maîtrisant ces techniques de développement, vous serez capable d\'intégrer une navigation dynamique et moderne tout en préservant une accessibilité optimale pour l\'ensemble de vos utilisateurs. C\'est l\'ouvrage idéal pour tout développeur souhaitant ajouter une touche de créativité professionnelle et de distinction à ses projets numériques.', 'gp2mv3', 0, 'covers/creer-un-menu-circulaire.png', 'books/creer-un-menu-circulaire.pdf', 9, 2010, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22');
INSERT INTO `books` (`id`, `title`, `slug`, `description`, `author`, `price`, `cover_path`, `file_path`, `nbr_pages`, `publish_year`, `is_published`, `category_id`, `created_at`, `updated_at`) VALUES
(59, 'Utiliser l\'API MySQL dans vos programmes', 'utiliser-lapi-mysql-dans-vos-programmes', 'Découvrez comment propulser vos applications C/C++ dans une nouvelle dimension en y intégrant la puissance et la flexibilité des bases de données MySQL. Ce guide pratique et accessible vous accompagne pas à pas, de la configuration de votre environnement de développement jusqu’à la maîtrise parfaite des connexions et des requêtes SQL au cœur de votre code. Que vous souhaitiez gérer des classements mondiaux ou des systèmes de données complexes, cet ouvrage vous donne les clés pour transformer vos programmes statiques en logiciels dynamiques, professionnels et évolutifs. C’est l’outil idéal pour tout développeur souhaitant franchir un cap technique et enrichir l\'interactivité de ses créations informatiques.', 'Henon Fabien', 0, 'covers/utiliser-l-api-mysql-dans-vos-programmes.png', 'books/utiliser-l-api-mysql-dans-vos-programmes.pdf', 18, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(60, 'Créer un petit montage avec Windows Movie Maker', 'creer-un-petit-montage-avec-windows-movie-maker', 'Découvrez comment transformer vos vidéos personnelles en montages réussis grâce à ce guide complet et accessible dédié à Windows Movie Maker. Conçu spécialement pour les débutants et les étudiants, ce manuel vous accompagne pas à pas dans la maîtrise de l\'interface, de l\'organisation de la chronologie jusqu\'à l\'exportation finale de vos projets. Vous y apprendrez à manipuler vos séquences avec aisance et à appliquer des astuces pratiques pour donner une dimension professionnelle à toutes vos présentations. C’est l’ouvrage idéal pour s’initier au montage vidéo de manière intuitive, gratuite et rapide.', 'Norrecix', 0, 'covers/creer-un-petit-montage-avec-windows-movie-maker.png', 'books/creer-un-petit-montage-avec-windows-movie-maker.pdf', 9, 2012, 1, 6, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(61, 'Animez votre site avec CSS3 !', 'animez-votre-site-avec-css3', 'Plongez dans l\'univers dynamique du webdesign moderne avec ce guide pratique dédié à la maîtrise des animations et transitions CSS3. À travers des exemples concrets allant du simple survol à la création de menus interactifs, vous apprendrez à transformer vos interfaces statiques en expériences fluides et captivantes pour vos utilisateurs. L\'ouvrage explore également l\'alliance puissante entre le CSS et le JavaScript pour vous offrir une liberté de création sans limites, tout en restant parfaitement accessible aux débutants. C\'est l\'outil indispensable pour tout développeur souhaitant donner une nouvelle dimension esthétique et professionnelle à ses projets web.', 'Adrien Guéret (KorHosik)', 0, 'covers/animez-votre-site-avec-css3.png', 'books/animez-votre-site-avec-css3.pdf', 21, 2011, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(62, 'Bien utiliser les sprites CSS', 'bien-utiliser-les-sprites-css', 'Découvrez comment optimiser les performances de vos sites web de manière innovante avec les sprites CSS. Ce guide pratique vous expliquera la technique consistant à regrouper astucieusement plusieurs images en une seule, réduisant ainsi drastiquement le nombre de requêtes HTTP et éliminant la latence des chargements. Apprenez à implémenter les sprites pour des animations au survol, des images répétées ou cliquables, et transformez votre approche du webdesign pour une expérience utilisateur plus fluide. Un ouvrage indispensable pour tout développeur souhaitant améliorer l\'efficacité de ses projets web.', 'warpShadow', 0, 'covers/bien-utiliser-les-sprites-css.png', 'books/bien-utiliser-les-sprites-css.pdf', 13, 2012, 1, 5, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(63, 'register_globals et écrasement de données', 'register-globals-et-ecrasement-de-donnees', 'La directive `register_globals` en PHP, bien que d\'apparence inoffensive, est une vulnérabilité majeure qui peut compromettre sérieusement la sécurité de vos applications web. Ce guide essentiel révèle comment une simple requête HTTP peut entraîner l\'écrasement de données sensibles ou même contourner vos systèmes d\'authentification, exposant ainsi vos informations confidentielles. Découvrez des méthodes concrètes pour désactiver cette directive sur votre serveur ou, si ce n\'est pas possible, apprenez à blinder votre code grâce à des pratiques de programmation sécurisées. Protégez vos utilisateurs et vos données en maîtrisant les risques liés à `register_globals` pour une sécurité optimale.', 'luc@s', 0, 'covers/register-globals-et-ecrasement-de-donnees.png', 'books/register-globals-et-ecrasement-de-donnees.pdf', 6, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(64, 'Le référencement de son site web', 'le-referencement-de-son-site-web', 'Préparez-vous à transformer la visibilité de votre site web ! Ce guide pratique vous offre les clés pour maîtriser le référencement et propulser vos pages en tête des résultats des moteurs de recherche. Des bases fondamentales aux techniques d\'optimisation \"in page\", apprenez pas à pas à décrypter les algorithmes et à appliquer les meilleures stratégies. Adoptez les bonnes pratiques du SEO pour attirer un trafic qualifié et faire de votre présence en ligne un véritable succès.', 'referenceur', 0, 'covers/le-referencement-de-son-site-web.png', 'books/le-referencement-de-son-site-web.pdf', 58, 2012, 1, 5, '2026-05-12 09:35:59', '2026-05-12 11:51:22'),
(65, 'Administrez vos bases de données avec MySQL', 'administrez-vos-bases-de-donnees-avec-mysql', '\"Administrez vos bases de données avec MySQL\" est le guide indispensable pour tout développeur ou administrateur souhaitant maîtriser le SGBDR le plus populaire du marché. De l\'installation complète sous divers OS à la prise en main du langage SQL pour créer, manipuler et sécuriser vos données, chaque concept est expliqué avec clarté. Vous explorerez également les techniques avancées comme les index pour optimiser les performances, les jointures complexes pour lier les informations, et les sous-requêtes pour des manipulations sophistiquées, vous offrant une expertise solide en administration de bases de données MySQL.', 'Chantal Gribaumont (Taguan)', 0, 'covers/administrez-vos-bases-de-donnees-avec-mysql.png', 'books/administrez-vos-bases-de-donnees-avec-mysql.pdf', 413, 2012, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:23'),
(66, 'Adapter son site au format mobile avec CSS3', 'adapter-son-site-au-format-mobile-avec-css3', 'Transformez votre site web en une interface moderne et parfaitement lisible sur smartphone grâce à ce guide pratique dédié aux techniques d\'optimisation mobile. En maîtrisant la puissance des media queries et des fonctionnalités avancées de CSS3, vous apprendrez à adapter vos mises en page avec précision pour offrir une expérience utilisateur fluide sur tous les types d\'écrans. De la configuration stratégique de la balise viewport à la création de menus dynamiques, cet ouvrage vous accompagne pas à pas à travers des exercices concrets pour professionnaliser vos projets web en un temps record. Que vous soyez débutant ou développeur autodidacte, ce manuel constitue l\'outil idéal pour rendre vos contenus accessibles et attractifs pour l\'ensemble de vos visiteurs mobiles.', 'SdaliM', 0, 'covers/adapter-son-site-au-format-mobile-avec-css3.png', 'books/adapter-son-site-au-format-mobile-avec-css3.pdf', 47, 2013, 1, 4, '2026-05-12 09:35:59', '2026-05-12 11:51:23'),
(67, 'Chiffrer des données avec TrueCrypt', 'chiffrer-des-donnees-avec-truecrypt', 'Vos données sensibles méritent une protection absolue contre les regards indiscrets et les menaces potentielles. Ce guide pratique vous ouvre les portes de TrueCrypt, un logiciel de chiffrement libre et puissant, pour sécuriser efficacement toutes vos informations. Apprenez pas à pas à créer des volumes chiffrés, des espaces de stockage invisibles et même à protéger des partitions entières, quel que soit votre système d\'exploitation. Offrez à vos documents personnels une confidentialité et une tranquillité d\'esprit inégalées grâce à des méthodes de chiffrement robustes et faciles à mettre en œuvre.', 'Mut', 0, 'covers/chiffrer-des-donnees-avec-truecrypt.png', 'books/chiffrer-des-donnees-avec-truecrypt.pdf', 10, 2009, 1, 7, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(68, 'Créez votre application web avec Java EE', 'creez-votre-application-web-avec-java-ee', 'Découvrez comment concevoir et déployer des applications web performantes et interactives grâce à ce guide pratique et complet sur Java EE. De l\'installation de votre environnement (Eclipse, Tomcat) aux bases du modèle MVC, ce livre vous équipe pour maîtriser les concepts clés tels que les Servlets, JSP et JavaBeans. Vous apprendrez à structurer vos projets, à gérer les formulaires et à utiliser la JSTL pour créer des interfaces utilisateur riches et dynamiques. Grâce à des exemples concrets et un projet fil rouge progressif, vous transformerez rapidement la théorie en applications web fonctionnelles.', 'Coyote', 0, 'covers/creez-votre-application-web-avec-java-ee.png', 'books/creez-votre-application-web-avec-java-ee.pdf', 606, 2013, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(69, 'Créer un menu horizontal déroulant en CSS', 'creer-un-menu-horizontal-deroulant-en-css', 'Envie d\'enrichir l\'interface de votre site web avec un menu de navigation moderne et interactif ? Ce guide complet vous plonge dans la création de menus horizontaux déroulants, en exploitant la puissance du xHTML et du CSS, complétée par une touche de JavaScript pour une compatibilité navigateur étendue. De la structuration des listes à l\'optimisation visuelle et fonctionnelle, vous apprendrez à concevoir des menus élégants et entièrement personnalisables. Préparez-vous à transformer l\'expérience utilisateur de votre site en maîtrisant la création de menus dynamiques et professionnels.', 'Antoine Estève (Toinouz)', 0, 'covers/creer-un-menu-horizontal-deroulant-en-css.png', 'books/creer-un-menu-horizontal-deroulant-en-css.pdf', 14, 2009, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(70, 'Générer des miniatures de pages web à la volée sur votre serveur web', 'generer-des-miniatures-de-pages-web-a-la-volee-sur-votre-serveur-web', 'Apprenez à automatiser la génération de miniatures de sites web en toute autonomie et affranchissez-vous des services tiers coûteux grâce à ce guide technique spécialisé. À travers une approche orientée console, vous découvrirez comment configurer un serveur graphique virtuel sous Linux pour capturer des visuels de haute qualité via des outils performants comme IceWeasel ou CutyCapt. Que vous gériez un annuaire ou un projet de grande envergure, cet ouvrage vous livre toutes les clés pour bâtir un système de capture robuste, scalable et entièrement gratuit. C\'est la ressource indispensable pour tout développeur ou administrateur système souhaitant optimiser ses ressources serveur avec une solution professionnelle et sur mesure.', 'Ving', 0, 'covers/generer-des-miniatures-de-pages-web-a-la-volee-sur-votre-serveur-web.png', 'books/generer-des-miniatures-de-pages-web-a-la-volee-sur-votre-serveur-web.pdf', 7, 2009, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(71, '[PHP5] Comment gérer l\'absence de surcharge ?', 'php5-comment-gerer-labsence-de-surcharge', 'Face à l\'absence de surcharge de méthodes en PHP5, concevoir des classes flexibles peut s\'avérer complexe. Ce guide pratique vous équipe des stratégies essentielles pour surmonter cette limitation, notamment pour la gestion des constructeurs et l\'implémentation de méthodes polyvalentes. Explorez des techniques éprouvées comme le comptage d\'arguments, le passage par tableau ou l\'usage d\'objets de validation, afin de développer un code orienté objet robuste et adaptable. Un ouvrage indispensable pour tout développeur PHP5 souhaitant optimiser la flexibilité et la maintenabilité de ses applications.', 'Legato', 0, 'covers/php5-comment-gerer-l-absence-de-surcharge.png', 'books/php5-comment-gerer-l-absence-de-surcharge.pdf', 11, 2010, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(72, 'Introduction à la logique mathématique', 'introduction-a-la-logique-mathematique', 'Plongez au cœur des fondements des mathématiques avec cette introduction complète à la logique. Ce guide clair et accessible vous dévoile les secrets des propositions, des opérateurs de base et des quantificateurs, essentiels pour tout raisonnement rigoureux. Apprenez à construire et analyser des arguments grâce à des méthodes clés comme la contraposée, le raisonnement par l\'absurde et par récurrence. Parfaitement adapté aux débutants, ce livre est votre passeport pour maîtriser l\'art de la pensée logique.', 'Le Zéro', 0, 'covers/introduction-a-la-logique-mathematique.png', 'books/654283-introduction-a-la-logique-mathematique.pdf', 24, 2012, 1, 6, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(73, 'Les tests unitaires en Java', 'les-tests-unitaires-en-java', 'Fatigué des bugs insaisissables dans votre code Java complexe ? Ce guide complet est votre allié indispensable pour maîtriser les tests unitaires et garantir la robustesse de vos applications. Il vous mènera pas à pas des définitions fondamentales à la mise en pratique avec JUnit, en explorant la couverture du code, la gestion avancée du contexte et l\'utilisation efficace des mocks. Apprenez à concevoir des tests unitaires solides et à développer une stratégie de test imparable, vous permettant d\'économiser un temps précieux et d\'améliorer considérablement la qualité de votre code. Cet ouvrage est essentiel pour tout développeur Java souhaitant bâtir des logiciels fiables et pérennes.', 'Hedi Radhouane (hedi07)', 0, 'covers/les-tests-unitaires-en-java.png', 'books/les-tests-unitaires-en-java.pdf', 30, 2012, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(74, 'Des statistiques pour votre site !', 'des-statistiques-pour-votre-site', 'Débloquez le plein potentiel de votre site web grâce à une analyse statistique approfondie ! Ce guide pratique et didactique vous équipe pour suivre précisément le nombre de visites, identifier les utilisateurs connectés et comprendre leur provenance. Vous apprendrez également à analyser les affluences et les heures de pointe pour optimiser vos campagnes de référencement et de publicité. Faites de vos données de trafic un atout stratégique pour faire rayonner votre plateforme.', 'Serialtueur', 0, 'covers/des-statistiques-pour-votre-site.png', 'books/des-statistiques-pour-votre-site.pdf', 15, 2010, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(75, 'Comprendre l\'USB et bricoler un périphérique', 'comprendre-lusb-et-bricoler-un-peripherique', 'Ce livre vous invite à démystifier le port USB, de ses origines à son fonctionnement détaillé, tout en vous lançant dans une création concrète. Explorez son histoire fascinante, ses différentes versions et types de connecteurs, ses schémas électriques précis et le protocole de communication complexe qui le rend si universel. Mettez ensuite la théorie en pratique en fabriquant un périphérique USB original et \"furtif\" : un ventilateur personnel qui vous rafraîchira discrètement. Idéal pour les curieux et les makers débutants, cet ouvrage vous offre une approche pédagogique et ludique pour maîtriser l\'USB et créer par vous-même.', 'OujA', 0, 'covers/comprendre-l-usb-et-bricoler-un-peripherique.png', 'books/comprendre-l-usb-et-bricoler-un-peripherique.pdf', 11, 2012, 1, 7, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(76, 'Les closures en Javascript', 'les-closures-en-javascript', 'Explorez les profondeurs des closures, un concept JavaScript crucial qui vous permettra de maîtriser la gestion des variables dans des scénarios complexes. Après une révision claire des fonctions et de la portée des variables, ce tutoriel vous guidera étape par étape dans la création et l\'utilisation efficace des closures, notamment pour les gestionnaires d\'événements et les fonctions de délai. Idéal pour tout développeur JavaScript souhaitant écrire un code plus robuste et éviter des erreurs fréquentes, ce guide pratique transforme un sujet complexe en une compétence accessible et immédiatement applicable.', 'Darkodam', 0, 'covers/les-closures-en-javascript.png', 'books/les-closures-en-javascript.pdf', 9, 2010, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(77, 'Apostille au MVC : les Delegate', 'apostille-au-mvc-les-delegate', 'Pour les développeurs C++ et Qt ayant déjà exploré les arcanes de l\'architecture Modèle-Vue, ce livre comble une lacune majeure en apportant une apostille essentielle à votre compréhension. Il se plonge au cœur des Delegates, ces composants puissants et souvent méconnus qui permettent une personnalisation inégalée de l\'affichage et de l\'édition des données dans vos vues Qt. Au-delà d\'une piqûre de rappel sur le MVC et sa mise en œuvre, vous apprendrez à maîtriser les Delegates existants, à comprendre leur mécanique interne, et à créer les vôtres pour des interfaces graphiques d\'une richesse et d\'une flexibilité exceptionnelles.', 'Mathieu STEFANI (Octal)', 0, 'covers/apostille-au-mvc-les-delegate.png', 'books/apostille-au-mvc-les-delegate.pdf', 17, 2011, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(78, 'Les maths pour tous !', 'les-maths-pour-tous', 'Vous en avez assez de considérer les mathématiques comme une matière obscure et inaccessible ? Découvrez \"Les maths pour tous !\", un ouvrage spécialement conçu pour vous accompagner de la 6ème à la Terminale. Loin des manuels scolaires complexes, il démystifie les concepts fondamentaux grâce à une approche pédagogique claire, des exemples concrets et des explications simples, répondant aux questions que vous vous posez vraiment. Retrouvez enfin le plaisir d\'apprendre et de maîtriser les chiffres, les fractions et l\'algèbre avec confiance.', 'Mathieu Nebra (Mateo21)', 0, 'covers/les-maths-pour-tous.png', 'books/les-maths-pour-tous.pdf', 77, 2011, 1, 6, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(79, 'CodeIgniter, le framework au service des Zéros', 'codeigniter-le-framework-au-service-des-zeros', 'Fatigué de repartir de zéro à chaque projet web ? Ce guide complet vous invite à maîtriser CodeIgniter, le framework PHP réputé pour sa rapidité et sa flexibilité, idéal pour les développeurs désireux d\'efficacité. De l\'architecture MVC et l\'installation à l\'utilisation avancée des contrôleurs, vues, modèles, helpers et bibliothèques, chaque composant est exploré avec des explications claires et des exemples concrets. Apprenez à développer rapidement des applications robustes, comme un livre d\'or complet, et découvrez des techniques avancées pour personnaliser et optimiser vos projets, transformant ainsi votre approche du développement web.', 'Nestea', 0, 'covers/codeigniter-le-framework-au-service-des-zeros.png', 'books/codeigniter-le-framework-au-service-des-zeros.pdf', 101, 2013, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(80, 'Structurez vos données avec XML', 'structurez-vos-donnees-avec-xml', 'Découvrez comment organiser et valider vos données de manière impeccable grâce à XML, le standard incontournable de structuration. Ce guide complet vous mène des bases de la syntaxe XML à la création de définitions robustes avec les DTD et Schémas XML, assurant ainsi l\'intégrité et la cohérence de vos informations. Grâce à des exemples concrets et des travaux pratiques, vous maîtriserez également l\'exploitation de vos données via les API DOM et XPath, illustrée par des applications en Java. Un ouvrage indispensable pour tout développeur souhaitant maîtriser la puissance de XML.', 'Ludovic ROLAND (Wapiti89)', 0, 'covers/structurez-vos-donnees-avec-xml.png', 'books/structurez-vos-donnees-avec-xml.pdf', 208, 2014, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(81, 'Gérer son nom de domaine', 'gerer-son-nom-de-domaine', 'Chaque site web possède une adresse, mais comprenez-vous réellement les rouages complexes de votre nom de domaine ? Ce guide essentiel vous invite à explorer les fondamentaux techniques, des adresses IP aux serveurs DNS, pour maîtriser l\'identité numérique de vos projets. Apprenez pas à pas à acquérir, configurer et même à installer votre propre serveur DNS, tout en gérant efficacement les zones et les enregistrements (A, CNAME, MX) de votre domaine. Devenez un expert autonome pour une présence en ligne robuste et pleinement contrôlée.', 'Mathieu Nebra (Mateo21)', 0, 'covers/gerer-son-nom-de-domaine.png', 'books/gerer-son-nom-de-domaine.pdf', 17, 2011, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(82, 'Créer un blog accessible avec HTML5', 'creer-un-blog-accessible-avec-html5', 'Vous connaissez HTML5 mais hésitez sur le bon usage des balises sémantiques pour construire un blog accessible ? Ce guide pratique, de difficulté facile, est fait pour vous ! Il vous accompagne pas à pas dans la création d\'une structure de blog impeccable, des pages aux articles et commentaires, en clarifiant l\'emploi des éléments HTML5 pertinents comme `<section>`, `<aside>` ou `<nav>`. Vous y découvrirez également les clés des normes d\'accessibilité ARIA et de la spécification Microdata, essentielles pour un site moderne, inclusif et optimisé.', 'Sébastien de la Marck (Thunderseb)', 0, 'covers/creer-un-blog-accessible-avec-html5.png', 'books/creer-un-blog-accessible-avec-html5.pdf', 21, 2012, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(83, 'Upload de fichiers par formulaire', 'upload-de-fichiers-par-formulaire', 'Donnez une nouvelle dimension à vos projets web en apprenant à maîtriser l\'envoi de fichiers par formulaire, de la conception de l\'interface à l\'intégration sécurisée sur votre serveur. Ce guide pédagogique vous accompagne pas à pas pour manipuler les données avec PHP, gérer le stockage en base de données et même automatiser la création de miniatures ou de compteurs de téléchargements. Grâce à des exemples concrets et des conseils pratiques, vous transformerez vos sites en plateformes interactives capables d\'héberger les documents de vos utilisateurs en toute sérénité. C’est la ressource indispensable pour tout développeur souhaitant franchir le cap de l\'interactivité avancée avec assurance et professionnalisme.', 'formulaire', 0, 'covers/upload-de-fichiers-par-formulaire.png', 'books/upload-de-fichiers-par-formulaire.pdf', 14, 2011, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(84, 'Créez des applications pour Android', 'creez-des-applications-pour-android', 'Prêt à donner vie à vos idées sur Android ? Ce guide complet vous emmène des fondations du développement mobile – de Java à la configuration de votre environnement – jusqu\'à la maîtrise des interfaces graphiques interactives et des fonctionnalités avancées. Enrichi de projets pratiques tels qu\'un bloc-notes ou une calculatrice d\'IMC, il vous dote des compétences essentielles pour concevoir des applications élégantes et fonctionnelles. Que vous soyez débutant ou que vous cherchiez à approfondir vos connaissances, ce livre est votre passeport pour l\'univers de la création d\'applications Android.', 'Frédéric Espiau (Apollidore)', 0, 'covers/creez-des-applications-pour-android.png', 'books/creez-des-applications-pour-android.pdf', 431, 2013, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(85, 'Tours de magie mathématiques', 'tours-de-magie-mathematiques', 'Envie d\'éblouir votre entourage avec des tours de magie qui ne nécessitent aucune dextérité, juste de la logique ? Ce livre captivant, \"Tours de magie mathématiques\", vous invite à explorer les astuces mathématiques derrière des illusions spectaculaires, des graphes bipartis aux permutations. Accessible à tous, quel que soit votre âge ou votre niveau en maths, il révèle comment des concepts de combinatoire et de probabilité se transforment en prodiges bluffants. Chaque tour est présenté avec son histoire, son explication détaillée et son fondement théorique, vous permettant de non seulement exécuter la magie, mais aussi de comprendre son secret.', 'Mickaël Launay (GéoMl17)', 0, 'covers/tours-de-magie-mathematiques.png', 'books/697154-tours-de-magie-mathematiques.pdf', 32, 2012, 1, 6, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(86, 'Les noms de domaine', 'les-noms-de-domaine', 'Vous avez créé votre site web et souhaitez le rendre accessible et mémorable en ligne ? Ce guide exhaustif est votre allié pour maîtriser l\'univers des noms de domaine, ces adresses incontournables du web. Il vous dévoilera leur fonctionnement détaillé, des types de domaines à la résolution via DNS, et vous accompagnera pas à pas dans le processus de réservation. Plongez dans les fondamentaux des noms de domaine et donnez une visibilité professionnelle et durable à votre projet numérique.', 'Pierre-Étienne Crépy (pierreet)', 0, 'covers/les-noms-de-domaine.png', 'books/les-noms-de-domaine.pdf', 8, 2011, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23'),
(87, 'Bonnes pratiques javascript', 'bonnes-pratiques-javascript', 'Votre code JavaScript est-il devenu un cauchemar à maintenir et à déboguer ? Ce guide essentiel, rédigé par des professionnels du web, vous plonge au cœur des meilleures pratiques pour transformer votre approche du développement. Apprenez à éviter les pièges courants, de l\'emplacement optimal de votre code à l\'usage judicieux de fonctions clés, et découvrez les règles de syntaxe qui garantissent clarté et performance. Adoptez des réflexes de codage propres et efficaces pour des projets JavaScript robustes et durables.', 'nod_', 0, 'covers/bonnes-pratiques-javascript.png', 'books/bonnes-pratiques-javascript.pdf', 13, 2012, 1, 4, '2026-05-12 09:36:00', '2026-05-12 11:51:23');

-- --------------------------------------------------------

--
-- Structure de la table `categories`
--

CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `categories`
--

INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Java', 'java', '2026-03-31 08:15:42', '2026-03-31 08:15:42'),
(2, 'Java Script', 'java-script', '2026-03-31 08:15:57', '2026-03-31 08:15:57'),
(3, 'WordPress', 'wordpress', '2026-03-31 08:16:10', '2026-03-31 08:16:10'),
(4, 'Développement', 'developpement', '2026-05-12 09:26:08', '2026-05-12 09:26:08'),
(5, 'Web Design', 'web-design', '2026-05-12 09:26:19', '2026-05-12 09:26:19'),
(6, 'Mathématiques', 'mathematiques', '2026-05-12 09:26:27', '2026-05-12 09:26:27'),
(7, 'Réseaux & Matériel', 'reseaux-materiel', '2026-05-12 09:26:37', '2026-05-12 09:26:37'),
(8, 'Bureautique', 'bureautique', '2026-05-12 09:26:48', '2026-05-12 09:26:48'),
(9, 'Serveur & BDD', 'serveur-bdd', '2026-05-12 09:27:00', '2026-05-12 09:27:00'),
(10, 'Informatique', 'informatique', '2026-05-12 09:27:07', '2026-05-12 09:27:07');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `books_slug_unique` (`slug`),
  ADD KEY `books_category_id_foreign` (`category_id`);

--
-- Index pour la table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `categories_slug_unique` (`slug`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `books`
--
ALTER TABLE `books`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=88;

--
-- AUTO_INCREMENT pour la table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `books`
--
ALTER TABLE `books`
  ADD CONSTRAINT `books_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
